name: Auto Assign PRs

on:
  pull_request:
    types: [opened, reopened]

  workflow_dispatch:
jobs:
  assignee:
    uses: clouddrove/github-shared-workflows/.github/workflows/auto_assignee.yml@fix/auto_assignee
    secrets:
      GITHUB: ${{ secrets.GITHUB }}
    with:
      assignees: 'clouddrove-ci'
      reviewers: |
            VishwajitNagulkar
            rishitz
